name: Build test

on:
  workflow_dispatch:
  watch:
   types: [started]

defaults:
  run:
   shell: bash

jobs:
 buildtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Swap Space
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: setup package
        run: |
         ./S

      - name: clean up
        run: |
         make clean; make mrproper

      - name: check clang version
        run: |
         clang -v

      - name: start up
        run: |
         ./build

      - name: anykernel ~ zipping
        run: |
         git clone https://github.com/Frostleaft07/AnyKernel3 -b Nethunter ~/any/
         mv ~/out/arch/arm64/boot/Image.gz-dtb ~/any/
         cd ~/any/ && rm -rf .git && zip -r9 Nethunter-v4.9.337.zip *

      - name: cloning KernelSU
        run: |
         curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s v0.9.5

      - name: start up ~ dirty build KernelSU
        run: |
         ./build

      - name: anykernel KernelSU ~ zipping
        run: |
         git clone https://github.com/Frostleaft07/AnyKernel3 -b KernelSU ~/ksu/
         mv ~/out/arch/arm64/boot/Image.gz-dtb ~/ksu/
         cd ~/ksu/ && rm -rf .git && zip -r9 Nethunter-v4.9.337-KernelSU-v0.9.5.zip *

      - name: upload to telegram [1/2]
        run: |
         curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendDocument" \
         -F chat_id="${{ secrets.CHAT_ID }}" \
         -F message_thread_id="${{ secrets.TOPIC_ID }}" \
         -F document=@"/home/runner/ksu/Nethunter-v4.9.337-KernelSU-v0.9.5.zip"

      - name: upload to telegram [2/2]
        run: |
         curl -s -X POST "https://api.telegram.org/bot${{ secrets.TG_TOKEN }}/sendDocument" \
         -F chat_id="${{ secrets.CHAT_ID }}" \
         -F message_thread_id="${{ secrets.TOPIC_ID }}" \
         -F document=@"/home/runner/any/Nethunter-v4.9.337.zip"
